[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "thecov"
description = 'A python package to compute analytic covariance matrices based on Wadekar & Scoccimarro 2019 (arXiv:1910.02914).'
version = "0.4.0"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Otavio Alves", email = 'oalves@umich.edu' },
    { name = "Joe Adamo", email = 'jadamo@arizona.edu'}
]
requires-python = ">= 3.9"
dependencies = ['numpy<2.0', 
                'scipy', 
                'tqdm',
                'Cython',
                'fitsio',
                'healpy',
                # We need a specific version of pfft-python (see https://github.com/MP-Gadget/pmesh/issues/53)
                'pfft-python==0.1.24',
                'pypower@git+https://github.com/cosmodesi/pypower',
                'pyclass@git+https://github.com/adematti/pyclass',
                "cosmoprimo@git+https://github.com/cosmodesi/cosmoprimo",
                'mockfactory@git+https://github.com/cosmodesi/mockfactory'
]

[tool.setuptools.packages.find]
where = ["thecov"]

[project.urls]
Homepage = "https://github.com/cosmodesi/thecov"