"""Every number quoted in the text: writes tex/numbers.tex with \\val{key} definitions (keys may contain / . _).
(Not named numbers.py: that would shadow the standard-library module.) Run after the figure scripts that save numbers_*.json (fig_fiber, fig_templates, fig_binning, fig_params)."""
import json
import os
from common import *

V = {}


def put(key, x, fmt='{:.3f}'):
    V[key] = fmt.format(x) if not isinstance(x, str) else x


put('Nmocks', len(holi('QSO', 'NGC')['V']), '{:d}')
put('nbins', holi('LRG1', 'NGC')['V'].shape[1], '{:d}')
put('wishart', 100 * np.sqrt(2 / (len(holi('LRG1', 'NGC')['V']) - 1)), '{:.1f}')
for b in ('LRG1', 'QSO'):
    for cap in ('NGC', 'SGC', 'GCcomb'):
        d = holi(b, cap)
        S = np.cov(d['V'].T)
        for m, C in d['C'].items():
            for km in (0.2, 0.3):
                I = kidx(d['k'], km)
                put(f'trace/{b}/{cap}/{m}/{km}', np.trace(np.linalg.solve(C[np.ix_(I, I)], S[np.ix_(I, I)])) / len(I))
        if cap != 'GCcomb':
            nb = len(d['k'])
            r = np.diag(d['C']['G']) / np.diag(d['C']['G_local'])
            put(f'kernelgain/{b}/{cap}', 100 * (r[:nb].mean() - 1), '{:.1f}')
            zz = load(f'holi_{b}')
            r = np.diag(zz[f'{cap}/x1/C_G_ownweight']) / np.diag(d['C']['G_local'])
            put(f'ownweight/{b}/{cap}', 100 * (r[:nb].mean() - 1), '{:.1f}')
            W, _ = whitened_cov(d['V'], d['C']['G'])
            put(f'lam1/{b}/{cap}/G', np.linalg.eigvalsh(W)[-1], '{:.1f}')
            W, _ = whitened_cov(d['V'], d['C']['rec'])
            put(f'lam1/{b}/{cap}/rec', np.linalg.eigvalsh(W)[-1], '{:.2f}')
            # amplitudes of P0 and P2 in units of their model error (recommended model)
            C = d['C']['rec']
            Ci = np.linalg.inv(C)
            mu = d['V'].mean(0)
            T = np.zeros((len(mu), 2))
            T[:nb, 0], T[nb:2 * nb, 1] = mu[:nb], mu[nb:2 * nb]
            Fi = np.linalg.inv(T.T @ Ci @ T)
            est = (Fi @ T.T @ Ci @ (d['V'] - mu).T).T
            vr = est.var(0, ddof=1) / np.diag(Fi)
            put(f'ampvar/{b}/{cap}/P0', vr[0], '{:.2f}')
            put(f'ampvar/{b}/{cap}/P2', vr[1], '{:.2f}')

# cross-validated variance along the two leading directions (same split as fig_clouds.py)
d = holi('LRG1', 'NGC')
Vv, N = d['V'], len(d['V'])
perm = np.random.default_rng(7).permutation(N)
A, B = Vv[perm[:N // 2]], Vv[perm[N // 2:]]
for m in ('G', 'rec'):
    W, Wi = whitened_cov(A, d['C'][m])
    lam, U = np.linalg.eigh(W)
    y = (Wi @ (B - B.mean(0)).T).T @ U[:, ::-1][:, :2]
    v = y.var(0, ddof=1)
    put(f'cv/LRG1/NGC/{m}/1', v[0], '{:.2f}')
    put(f'cv/LRG1/NGC/{m}/2', v[1], '{:.2f}')
    put(f'insample/LRG1/NGC/{m}/1', lam[-1], '{:.2f}')
put('cverr', np.sqrt(2 / (N // 2 - 1)), '{:.2f}')

put('Nexcluded', len(excluded('LRG1')), '{:d}')
put('Nclean', len(holi('LRG1', 'NGC')['V']), '{:d}')
z = load('nz_scatter_LRG1')
okz = ~np.isin(z['NGC/mocks'], excluded('LRG1'))
put('nzcapcorr/LRG1', np.corrcoef(z['NGC/NZ'][okz].sum(1), z['SGC/NZ'][okz].sum(1))[0, 1], '{:.2f}')
z = load('nz_scatter_QSO')
put('nzcapcorr/QSO', np.corrcoef(z['NGC/NZ'].sum(1), z['SGC/NZ'].sum(1))[0, 1], '{:.2f}')
put('nNZmocks', len(z['NGC/mocks']), '{:d}')

for name in ('fiber', 'templates', 'binning', 'params', 'nz'):
    fn = os.path.join(PROD, f'numbers_{name}.json')
    if not os.path.exists(fn):
        print(f'{fn} missing (run fig_{name}.py first)')
        continue
    js = json.load(open(fn))
    if name == 'fiber':
        for cap, v in js.items():
            put(f'fiber/{cap}/diff', v['diff'], '{:+.3f}')
            put(f'fiber/{cap}/differr', v['diff_err'], '{:.3f}')
            put(f'fiber/{cap}/corr', v['corr'], '{:.2f}')
    elif name == 'templates':
        for key, v in js.items():
            ds, fit = key.split('/', 1)
            fit = {'SSC + disc': 'base', r'+ tree $T_0$': 'tree', r'+ response $T_0$': 'resp'}[fit]
            for t in v['theta']:
                put(f'tpl/{ds.replace(" ", "_")}/{fit}/{t}', v['theta'][t], '{:.2f}')
                put(f'tplerr/{ds.replace(" ", "_")}/{fit}/{t}', v['sigma'][t], '{:.2f}')
    elif name == 'binning':
        for key, v in js.items():
            for f, t in zip((1, 2, 4), v['trace']):
                put(f'bintrace/{key}/x{f}', t)
    elif name == 'nz':
        for key, v in js.items():
            for sc, r in zip(v['scale'], v['ratio']):
                put(f'nz/{key}/{sc:.0f}', r, '{:.2f}')
    elif name == 'params':
        for key, v in js.items():
            for km in ('0.200', '0.300'):
                for j, p in enumerate(('A', 'A2', 'alpha', 'SN')):
                    put(f'par/{key}/{km}/{p}', v[km][j], '{:.2f}')

os.makedirs(os.path.join(ROOT, 'tex'), exist_ok=True)
with open(os.path.join(ROOT, 'tex', 'numbers.tex'), 'w') as fh:
    fh.write(f'% generated by paper/scripts/numbers.py @ {git_commit()} -- do not edit\n')
    for k, v in sorted(V.items()):
        fh.write(f'\\expandafter\\def\\csname val@{k}\\endcsname{{{v}}}\n')
print(f'wrote tex/numbers.tex ({len(V)} values)')
